# Generated by Django 3.0.8 on 2020-09-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sem1',
            fields=[
                ('enroll_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ECAS130C_T', models.CharField(blank=True, max_length=2)),
                ('SCDE130C_T', models.CharField(blank=True, max_length=2)),
                ('EEDC132C_T', models.CharField(blank=True, max_length=2)),
                ('IIPG132C_T', models.CharField(blank=True, max_length=2)),
                ('SEGP132C_T', models.CharField(blank=True, max_length=2)),
                ('IITC102C_L', models.CharField(blank=True, max_length=2)),
                ('IIPG132C_L', models.CharField(blank=True, max_length=2)),
                ('SEGP132C_L', models.CharField(blank=True, max_length=2)),
                ('MPCN102C_L', models.CharField(blank=True, max_length=2)),
                ('SGPI', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
