# Generated by Django 3.0.8 on 2020-09-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sem1',
            options={'verbose_name_plural': 'Semester 1'},
        ),
        migrations.AddField(
            model_name='sem1',
            name='EEDC132C_L',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
