# Generated by Django 3.0.8 on 2020-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200903_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem1',
            name='SGPI',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
