# Generated by Django 3.0.8 on 2020-09-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200903_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem2',
            fields=[
                ('enroll_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('SPAS230C_T', models.CharField(blank=True, max_length=2)),
                ('IDMA230C_T', models.CharField(blank=True, max_length=2)),
                ('EDES232C_T', models.CharField(blank=True, max_length=2)),
                ('MPOM230C_T', models.CharField(blank=True, max_length=2)),
                ('ICOA230C_T', models.CharField(blank=True, max_length=2)),
                ('IDST232C_T', models.CharField(blank=True, max_length=2)),
                ('EDES232C_L', models.CharField(blank=True, max_length=2)),
                ('IDST232C_L', models.CharField(blank=True, max_length=2)),
                ('SGPI', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Semester 2',
            },
        ),
        migrations.CreateModel(
            name='Sem3',
            fields=[
                ('enroll_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('IOPS332C_T', models.CharField(blank=True, max_length=2)),
                ('SMAT330C_T', models.CharField(blank=True, max_length=2)),
                ('IOOM330C_T', models.CharField(blank=True, max_length=2)),
                ('EMIP332C_T', models.CharField(blank=True, max_length=2)),
                ('ITOC330C_T', models.CharField(blank=True, max_length=2)),
                ('IOPS332C_L', models.CharField(blank=True, max_length=2)),
                ('IOOM332C_L', models.CharField(blank=True, max_length=2)),
                ('EMIP332C_L', models.CharField(blank=True, max_length=2)),
                ('SGPI', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Semester 3',
            },
        ),
        migrations.CreateModel(
            name='Sem4',
            fields=[
                ('enroll_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('IDAA432C_T', models.CharField(blank=True, max_length=2)),
                ('SMAT430C_T', models.CharField(blank=True, max_length=2)),
                ('EPCO432C_T', models.CharField(blank=True, max_length=2)),
                ('IDBM432C_T', models.CharField(blank=True, max_length=2)),
                ('IPPL430C_T', models.CharField(blank=True, max_length=2)),
                ('IDAA432C_L', models.CharField(blank=True, max_length=2)),
                ('EPCO432C_L', models.CharField(blank=True, max_length=2)),
                ('IDBM432C_L', models.CharField(blank=True, max_length=2)),
                ('SGPI', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Semester 4',
            },
        ),
        migrations.CreateModel(
            name='Sem5',
            fields=[
                ('enroll_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('ECAS130C_T', models.CharField(blank=True, max_length=2)),
                ('SCDE130C_T', models.CharField(blank=True, max_length=2)),
                ('EEDC132C_T', models.CharField(blank=True, max_length=2)),
                ('IIPG132C_T', models.CharField(blank=True, max_length=2)),
                ('SEGP132C_T', models.CharField(blank=True, max_length=2)),
                ('IITC102C_L', models.CharField(blank=True, max_length=2)),
                ('EEDC132C_L', models.CharField(blank=True, max_length=2)),
                ('IIPG132C_L', models.CharField(blank=True, max_length=2)),
                ('SEGP132C_L', models.CharField(blank=True, max_length=2)),
                ('MPCN102C_L', models.CharField(blank=True, max_length=2)),
                ('SGPI', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Semester 5',
            },
        ),
        migrations.CreateModel(
            name='Sem6',
            fields=[
                ('enroll_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('ECAS130C_T', models.CharField(blank=True, max_length=2)),
                ('SCDE130C_T', models.CharField(blank=True, max_length=2)),
                ('EEDC132C_T', models.CharField(blank=True, max_length=2)),
                ('IIPG132C_T', models.CharField(blank=True, max_length=2)),
                ('SEGP132C_T', models.CharField(blank=True, max_length=2)),
                ('IITC102C_L', models.CharField(blank=True, max_length=2)),
                ('EEDC132C_L', models.CharField(blank=True, max_length=2)),
                ('IIPG132C_L', models.CharField(blank=True, max_length=2)),
                ('SEGP132C_L', models.CharField(blank=True, max_length=2)),
                ('MPCN102C_L', models.CharField(blank=True, max_length=2)),
                ('SGPI', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Semester 6',
            },
        ),
        migrations.CreateModel(
            name='Sem7',
            fields=[
                ('enroll_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('ECAS130C_T', models.CharField(blank=True, max_length=2)),
                ('SCDE130C_T', models.CharField(blank=True, max_length=2)),
                ('EEDC132C_T', models.CharField(blank=True, max_length=2)),
                ('IIPG132C_T', models.CharField(blank=True, max_length=2)),
                ('SEGP132C_T', models.CharField(blank=True, max_length=2)),
                ('IITC102C_L', models.CharField(blank=True, max_length=2)),
                ('EEDC132C_L', models.CharField(blank=True, max_length=2)),
                ('IIPG132C_L', models.CharField(blank=True, max_length=2)),
                ('SEGP132C_L', models.CharField(blank=True, max_length=2)),
                ('MPCN102C_L', models.CharField(blank=True, max_length=2)),
                ('SGPI', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Semester 7',
            },
        ),
        migrations.AlterModelOptions(
            name='sem1',
            options={'verbose_name_plural': 'Semester 8'},
        ),
        migrations.AlterField(
            model_name='sem1',
            name='enroll_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Enrollment Number'),
        ),
    ]
