# Generated by Django 3.0.8 on 2020-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200904_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem8',
            fields=[
                ('enroll_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Enrollment Number')),
                ('ECAS130C_T', models.CharField(blank=True, max_length=2)),
                ('SCDE130C_T', models.CharField(blank=True, max_length=2)),
                ('EEDC132C_T', models.CharField(blank=True, max_length=2)),
                ('IIPG132C_T', models.CharField(blank=True, max_length=2)),
                ('SEGP132C_T', models.CharField(blank=True, max_length=2)),
                ('IITC102C_L', models.CharField(blank=True, max_length=2)),
                ('EEDC132C_L', models.CharField(blank=True, max_length=2)),
                ('IIPG132C_L', models.CharField(blank=True, max_length=2)),
                ('SEGP132C_L', models.CharField(blank=True, max_length=2)),
                ('MPCN102C_L', models.CharField(blank=True, max_length=2)),
                ('SGPI', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Semester 8',
            },
        ),
        migrations.AlterModelOptions(
            name='sem1',
            options={'verbose_name_plural': 'Semester 1'},
        ),
    ]
