# Generated by Django 3.0.8 on 2020-11-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201110_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='elective',
            name='semester',
            field=models.IntegerField(default='6'),
        ),
    ]
