# Generated by Django 3.0.8 on 2020-11-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('file', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Announcements',
            },
        ),
    ]
