# Generated by Django 3.0.8 on 2020-11-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/%Y %m %d/'),
        ),
    ]
