# Generated by Django 3.0.8 on 2020-11-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20201114_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={},
        ),
    ]
