# Generated by Django 3.0.8 on 2020-11-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20201114_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name_plural': 'Announcements'},
        ),
    ]
