# Generated by Django 3.0.8 on 2020-11-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_auto_20201114_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('file', models.FileField(blank=True, upload_to='uploads/%Y %m %d/')),
            ],
            options={
                'verbose_name_plural': 'Syllabus',
            },
        ),
    ]
