# Generated by Django 3.0.8 on 2020-11-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('file', models.FileField(upload_to='uploads/%Y %m %d/')),
            ],
            options={
                'verbose_name_plural': 'Question Papers',
            },
        ),
    ]
